// This is the main entry file of the lib.

// "index.ts" is an autogenerated http client, which we can't monkey patch.
export * from './index'
export type * from './index'

// Bellow extra exports beyond autogenerated http client.
export {
  fullQuoteHash,
  verifyQuoteSignature,
} from './quote-signature';
export type {
  OneClickQuote,
  OneClickQuoteRequest,
  OneClickQuoteResponse,
  VerifyQuoteSignatureResult,
} from './quote-signature';